/**
 * The anti-drift mechanism.
 *
 * The editor (TypeScript) and the runtime (Rust) each decide whether a connection is legal.
 * Both read `data/type-graph.json`, but reading the same data is not the same as agreeing:
 * two implementations of the same rules drift, and the failure is silent and horrible — the
 * editor lets you build a graph the runtime refuses, or worse, the editor forbids something
 * the runtime would happily have done.
 *
 * So the TypeScript side writes down its answer for every pair it is asked about, and the
 * Rust side replays that file and asserts it agrees (`crates/encastra-protocol/tests/
 * conformance.rs`). A divergence fails somebody's build on the commit that caused it.
 *
 * To regenerate after an intentional rule change:  UPDATE_MATRIX=1 npx vitest run
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { allTypes, checkCompatibility } from '../src/type-graph.js';

const MATRIX_PATH = fileURLToPath(new URL('../data/compat-matrix.json', import.meta.url));

interface Entry {
  readonly from: string;
  readonly to: string;
  readonly ok: boolean;
  readonly kind: string | null;
  readonly ops: readonly string[];
}

/** Composite shapes worth pinning, on top of every named type. */
const COMPOSITES = [
  'list<image>',
  'list<file>',
  'list<i64>',
  'list<string>',
  'option<string>',
  'option<image>',
  'option<i64>',
  'list<option<file>>',
] as const;

function buildMatrix(): Entry[] {
  const exprs = [...[...allTypes().keys()].sort(), ...COMPOSITES];
  const entries: Entry[] = [];
  for (const from of exprs) {
    for (const to of exprs) {
      const r = checkCompatibility(from, to);
      entries.push(
        r.ok
          ? { from, to, ok: true, kind: r.kind, ops: r.ops }
          : { from, to, ok: false, kind: null, ops: [] },
      );
    }
  }
  return entries;
}

describe('cross-language conformance matrix', () => {
  const matrix = buildMatrix();

  it('is committed and up to date', () => {
    const serialised = `${JSON.stringify(
      {
        $comment:
          'GENERATED by packages/protocol/test/conformance-matrix.test.ts. Do not edit by hand. Regenerate with UPDATE_MATRIX=1 npx vitest run. crates/encastra-protocol/tests/conformance.rs asserts the Rust implementation agrees with every entry.',
        generatedFrom: 'packages/protocol/data/type-graph.json',
        entries: matrix,
      },
      null,
      2,
    )}\n`;

    if (process.env.UPDATE_MATRIX === '1') {
      writeFileSync(MATRIX_PATH, serialised, 'utf8');
      return;
    }

    expect(
      existsSync(MATRIX_PATH),
      'compat-matrix.json is missing — run UPDATE_MATRIX=1 npx vitest run',
    ).toBe(true);
    expect(
      readFileSync(MATRIX_PATH, 'utf8'),
      'The type rules changed but the conformance matrix was not regenerated. Run UPDATE_MATRIX=1 npx vitest run, and expect the Rust conformance test to tell you if the runtime disagrees.',
    ).toBe(serialised);
  });

  it('covers every ordered pair of the shapes it claims to cover', () => {
    const count = allTypes().size + COMPOSITES.length;
    expect(matrix).toHaveLength(count * count);
  });

  it('is self-consistent: every type reaches itself directly', () => {
    for (const entry of matrix) {
      if (entry.from !== entry.to) continue;
      expect(entry, `${entry.from} does not connect to itself`).toMatchObject({
        ok: true,
        kind: 'direct',
        ops: [],
      });
    }
  });

  it('records at least one refusal, so a matrix of all-yes is caught', () => {
    // A rule change that accidentally made everything connectable would otherwise pass every
    // other assertion in this file.
    expect(matrix.some((e) => !e.ok)).toBe(true);
  });
});
