//! Connection legality, runtime side.
//!
//! This crate and `packages/protocol` (TypeScript) answer the same question: may a value of
//! type A flow into a port of type B? They **must** agree — an editor that permits a
//! connection the runtime then rejects is worse than one that is simply strict.
//!
//! They agree by construction: both read `packages/protocol/data/type-graph.json`, which is
//! embedded here at compile time. Neither hardcodes a pair. On top of that, `tests/
//! conformance.rs` replays a matrix generated by the TypeScript implementation and asserts
//! this one produces the same answer for every entry, so drift fails the build rather than
//! surfacing as a confusing bug months later.

use std::collections::{BTreeMap, BTreeSet};
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

pub mod manifest;

/// The shared rule table, embedded from the same file the TypeScript side imports.
const TYPE_GRAPH_JSON: &str = include_str!("../../../packages/protocol/data/type-graph.json");

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CoercionKind {
    /// Same type, or a widening. Nothing happens at run time.
    Direct,
    /// A total conversion that cannot fail. Applied automatically.
    Implicit,
    /// May fail or lose information. Materialised as a Convert node the user can see.
    Explicit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TypeKind {
    Scalar,
    Handle,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeDef {
    pub kind: TypeKind,
    pub label: String,
    pub color: String,
    pub doc: String,
    #[serde(default, rename = "extends")]
    pub extends_: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Coercion {
    pub from: String,
    pub to: String,
    pub kind: CoercionKind,
    pub op: String,
    #[serde(default)]
    pub note: Option<String>,
}

#[derive(Debug, Deserialize)]
struct TypeGraphFile {
    schema: u32,
    types: BTreeMap<String, TypeDef>,
    coercions: Vec<Coercion>,
}

/// The protocol revision this build understands. A manifest declaring a higher `schema` is
/// refused rather than parsed on a guess.
pub const SCHEMA_VERSION: u32 = 1;

struct TypeGraph {
    types: BTreeMap<String, TypeDef>,
    coercions: BTreeMap<(String, String), Coercion>,
}

static GRAPH: LazyLock<TypeGraph> = LazyLock::new(|| {
    let file: TypeGraphFile = serde_json::from_str(TYPE_GRAPH_JSON)
        .expect("type-graph.json is embedded at compile time and must parse");
    assert_eq!(
        file.schema, SCHEMA_VERSION,
        "type-graph.json declares schema {} but this build implements {}",
        file.schema, SCHEMA_VERSION
    );
    let coercions = file
        .coercions
        .into_iter()
        .map(|c| ((c.from.clone(), c.to.clone()), c))
        .collect();
    TypeGraph {
        types: file.types,
        coercions,
    }
});

// ---------------------------------------------------------------------------------------
// Type expressions
// ---------------------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TypeExpr {
    Named(String),
    List(Box<TypeExpr>),
    Opt(Box<TypeExpr>),
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[error("{message} (in \"{input}\" at {position})")]
pub struct TypeSyntaxError {
    pub message: String,
    pub input: String,
    pub position: usize,
}

/// Parse a port type expression. Grammar: `ident | list<expr> | option<expr>`.
pub fn parse_type(input: &str) -> Result<TypeExpr, TypeSyntaxError> {
    let bytes = input.as_bytes();
    let (expr, end) = parse_at(input, bytes, 0)?;
    if input[end..].trim().is_empty() {
        Ok(expr)
    } else {
        Err(err("unexpected trailing input", input, end))
    }
}

fn err(message: &str, input: &str, position: usize) -> TypeSyntaxError {
    TypeSyntaxError {
        message: message.to_owned(),
        input: input.to_owned(),
        position,
    }
}

fn parse_at(input: &str, bytes: &[u8], start: usize) -> Result<(TypeExpr, usize), TypeSyntaxError> {
    let mut i = skip_space(bytes, start);
    let name_start = i;
    if i >= bytes.len() || !bytes[i].is_ascii_lowercase() {
        return Err(err("expected a type name", input, i));
    }
    i += 1;
    while i < bytes.len()
        && (bytes[i].is_ascii_lowercase() || bytes[i].is_ascii_digit() || bytes[i] == b'_')
    {
        i += 1;
    }
    let name = &input[name_start..i];
    let generic = matches!(name, "list" | "option");

    let after_name = skip_space(bytes, i);
    if after_name >= bytes.len() || bytes[after_name] != b'<' {
        if generic {
            return Err(err(
                &format!("\"{name}\" requires a type argument, e.g. {name}<string>"),
                input,
                i,
            ));
        }
        return Ok((TypeExpr::Named(name.to_owned()), i));
    }
    if !generic {
        return Err(err(
            &format!("\"{name}\" does not take a type argument"),
            input,
            after_name,
        ));
    }

    let (item, after_item) = parse_at(input, bytes, after_name + 1)?;
    let close = skip_space(bytes, after_item);
    if close >= bytes.len() || bytes[close] != b'>' {
        return Err(err("expected \">\"", input, close));
    }
    let expr = if name == "list" {
        TypeExpr::List(Box::new(item))
    } else {
        TypeExpr::Opt(Box::new(item))
    };
    Ok((expr, close + 1))
}

fn skip_space(bytes: &[u8], from: usize) -> usize {
    let mut i = from;
    while i < bytes.len() && bytes[i] == b' ' {
        i += 1;
    }
    i
}

pub fn format_type(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::Named(n) => n.clone(),
        TypeExpr::List(i) => format!("list<{}>", format_type(i)),
        TypeExpr::Opt(i) => format!("option<{}>", format_type(i)),
    }
}

// ---------------------------------------------------------------------------------------
// Compatibility
// ---------------------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Compatible {
    pub kind: CoercionKind,
    /// Conversion operations the runtime applies, outermost first.
    pub ops: Vec<String>,
    pub note: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Compatibility {
    Yes(Compatible),
    No {
        reason: String,
        bridges: Vec<String>,
    },
}

impl Compatibility {
    pub fn is_ok(&self) -> bool {
        matches!(self, Compatibility::Yes(_))
    }
}

pub fn type_def(name: &str) -> Option<&'static TypeDef> {
    GRAPH.types.get(name)
}

pub fn is_known_type(name: &str) -> bool {
    GRAPH.types.contains_key(name)
}

pub fn all_type_names() -> impl Iterator<Item = &'static String> {
    GRAPH.types.keys()
}

/// Every declared coercion.
///
/// Exposed so that the runtime can assert it implements each one — a table that declares an
/// operation nothing can execute would otherwise produce an edge the editor accepts and the
/// run cannot perform.
pub fn all_coercions() -> impl Iterator<Item = &'static Coercion> {
    GRAPH.coercions.values()
}

/// `image` -> `["image", "file"]`. A type is its own first ancestor.
pub fn ancestors_of(name: &str) -> Vec<String> {
    let mut chain = Vec::new();
    let mut seen = BTreeSet::new();
    let mut current = Some(name.to_owned());
    while let Some(t) = current {
        if !seen.insert(t.clone()) {
            break;
        }
        current = GRAPH.types.get(&t).and_then(|d| d.extends_.clone());
        chain.push(t);
    }
    chain
}

fn is_strict_descendant(sub: &str, sup: &str) -> bool {
    sub != sup && ancestors_of(sub).iter().any(|a| a == sup)
}

/// Can a value of type `from` flow into a port of type `to`?
pub fn check_compatibility(from: &TypeExpr, to: &TypeExpr) -> Compatibility {
    check(from, to)
}

/// Convenience wrapper that parses both sides first.
pub fn check_compatibility_str(from: &str, to: &str) -> Compatibility {
    let a = match parse_type(from) {
        Ok(e) => e,
        Err(e) => {
            return Compatibility::No {
                reason: e.to_string(),
                bridges: Vec::new(),
            };
        }
    };
    let b = match parse_type(to) {
        Ok(e) => e,
        Err(e) => {
            return Compatibility::No {
                reason: e.to_string(),
                bridges: Vec::new(),
            };
        }
    };
    check(&a, &b)
}

fn check(a: &TypeExpr, b: &TypeExpr) -> Compatibility {
    if a == b {
        return Compatibility::Yes(Compatible {
            kind: CoercionKind::Direct,
            ops: Vec::new(),
            note: None,
        });
    }

    match (a, b) {
        // T -> option<T>: wrapping a present value is free.
        (other, TypeExpr::Opt(inner)) if !matches!(other, TypeExpr::Opt(_)) => check(other, inner),

        // option<T> -> U: the absent case has to be handled where a person can see it.
        (TypeExpr::Opt(inner), other) if !matches!(other, TypeExpr::Opt(_)) => {
            match check(inner, other) {
                no @ Compatibility::No { .. } => no,
                Compatibility::Yes(c) => {
                    let mut ops = vec!["unwrap-option".to_owned()];
                    ops.extend(c.ops);
                    Compatibility::Yes(Compatible {
                        kind: CoercionKind::Explicit,
                        ops,
                        note: Some(
                            "This value may be absent. The Convert node decides what happens when it is."
                                .to_owned(),
                        ),
                    })
                }
            }
        }

        (TypeExpr::Opt(x), TypeExpr::Opt(y)) => check(x, y),

        (TypeExpr::List(x), TypeExpr::List(y)) => match check(x, y) {
            Compatibility::No { reason, bridges } => Compatibility::No {
                reason: format!("Lists do not match: {reason}"),
                bridges,
            },
            Compatibility::Yes(c) if c.kind == CoercionKind::Direct => Compatibility::Yes(c),
            Compatibility::Yes(c) => {
                let mut ops = vec!["map".to_owned()];
                ops.extend(c.ops);
                Compatibility::Yes(Compatible {
                    kind: c.kind,
                    ops,
                    note: c.note,
                })
            }
        },

        (TypeExpr::Named(x), TypeExpr::Named(y)) => check_named(x, y),

        _ => Compatibility::No {
            reason: format!("{} cannot connect to {}.", format_type(a), format_type(b)),
            bridges: Vec::new(),
        },
    }
}

/// The decision alone, with no explanation attached — pure, and it never calls back into the
/// explaining layer. Keeping these apart is what stops `check_named` and `find_bridges` from
/// calling each other forever.
fn resolve_named(from: &str, to: &str) -> Option<Compatible> {
    let mut best: Option<Compatible> = None;

    // A value is also a value of each of its supertypes, so try the coercion table from every
    // ancestor. Widening is free. One coercion hop, never a chain.
    for ancestor in ancestors_of(from) {
        if ancestor == to {
            best = pick_better(
                best,
                Compatible {
                    kind: CoercionKind::Direct,
                    ops: Vec::new(),
                    note: None,
                },
            );
            continue;
        }

        let Some(coercion) = GRAPH.coercions.get(&(ancestor.clone(), to.to_owned())) else {
            continue;
        };

        // Widening and then narrowing lands on a sibling: image -> file -> video would let an
        // Image connect to a Video port and fail on every run. Refuse it in the editor.
        if ancestor != from && is_strict_descendant(to, &ancestor) {
            continue;
        }

        best = pick_better(
            best,
            Compatible {
                kind: coercion.kind,
                ops: vec![coercion.op.clone()],
                note: coercion.note.clone(),
            },
        );
    }

    best
}

fn pick_better(current: Option<Compatible>, candidate: Compatible) -> Option<Compatible> {
    match current {
        None => Some(candidate),
        Some(c) if candidate.kind < c.kind => Some(candidate),
        Some(c) => Some(c),
    }
}

fn check_named(from: &str, to: &str) -> Compatibility {
    for name in [from, to] {
        if !is_known_type(name) {
            return Compatibility::No {
                reason: format!(
                    "\"{name}\" is not a type this runtime knows. The component may need a newer runtime version."
                ),
                bridges: Vec::new(),
            };
        }
    }

    match resolve_named(from, to) {
        Some(c) => Compatibility::Yes(c),
        None => Compatibility::No {
            reason: describe_failure(from, to),
            bridges: find_bridges(from, to),
        },
    }
}

fn label(name: &str) -> String {
    GRAPH
        .types
        .get(name)
        .map(|d| d.label.clone())
        .unwrap_or_else(|| name.to_owned())
}

fn describe_failure(from: &str, to: &str) -> String {
    let to_ancestors = ancestors_of(to);
    let shared = ancestors_of(from)
        .into_iter()
        .find(|t| to_ancestors.contains(t));
    match shared {
        Some(s) if s != from && s != to => format!(
            "{} and {} are both kinds of {}, but one is not the other. Convert through {} if that is what you mean.",
            label(from),
            label(to),
            label(&s),
            label(&s)
        ),
        _ => format!(
            "{} cannot become {}. There is no conversion between them.",
            label(from),
            label(to)
        ),
    }
}

fn find_bridges(from: &str, to: &str) -> Vec<String> {
    GRAPH
        .types
        .keys()
        .filter(|c| c.as_str() != from && c.as_str() != to)
        .filter(|c| resolve_named(from, c).is_some() && resolve_named(c, to).is_some())
        .cloned()
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn kind_of(from: &str, to: &str) -> Option<CoercionKind> {
        match check_compatibility_str(from, to) {
            Compatibility::Yes(c) => Some(c.kind),
            Compatibility::No { .. } => None,
        }
    }

    #[test]
    fn parses_and_formats() {
        for s in ["string", "list<image>", "option<f64>", "list<option<file>>"] {
            assert_eq!(format_type(&parse_type(s).unwrap()), s);
        }
        assert!(parse_type("list<").is_err());
        assert!(parse_type("list").is_err());
        assert!(parse_type("image<string>").is_err());
        assert!(parse_type("").is_err());
    }

    #[test]
    fn widens_but_never_narrows_to_a_sibling() {
        assert_eq!(kind_of("image", "file"), Some(CoercionKind::Direct));
        assert_eq!(kind_of("image", "video"), None);
        assert_eq!(kind_of("image", "i64"), None);
    }

    #[test]
    fn fallible_conversions_are_explicit() {
        assert_eq!(kind_of("i64", "string"), Some(CoercionKind::Implicit));
        assert_eq!(kind_of("string", "i64"), Some(CoercionKind::Explicit));
    }

    #[test]
    fn options_and_lists_compose() {
        assert_eq!(
            kind_of("string", "option<string>"),
            Some(CoercionKind::Direct)
        );
        assert_eq!(
            kind_of("option<string>", "string"),
            Some(CoercionKind::Explicit)
        );
        assert_eq!(
            kind_of("list<image>", "list<file>"),
            Some(CoercionKind::Direct)
        );
        assert_eq!(kind_of("list<image>", "list<i64>"), None);
    }

    #[test]
    fn terminates_on_an_impossible_pair() {
        // Regression: deciding and explaining used to call each other without a base case.
        assert!(!check_compatibility_str("image", "i64").is_ok());
    }
}
